<?xml version="1.0"?>
<robot
  xmlns:xacro="http://ros.org/wiki/xacro"
  name="kurtana">
  
  <xacro:property name="top_y_offset" value="0.00" />
  <xacro:property name="base_z_offset" value="0.00" /> <!-- distance from base_link to top of cover surface -->

  <xacro:include filename="$(find kurt_base)/urdf/kurt_outdoor.urdf.xacro" />
  <xacro:include filename="$(find kurtana_description)/tops/kurtana_top.urdf.xacro" />

  <joint name="top_base_joint" type="fixed">
    <parent link="base_link" />
    <child link="kurtana_rackplate_link" />
    <origin xyz="0 ${top_y_offset} ${base_z_offset + rackplate_height/2}" />
  </joint>

</robot>
